version: '3.8'

services:
  web:
    build: .
    command: gunicorn QnAChatBot.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  media_volume:
  static_volume: